name: Build and Create Release

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
          dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true
          dotnet publish -c Release -r osx-x64 --self-contained true /p:PublishSingleFile=true

      - name: Rename binaries
        run: |
          mv SyatiModuleBuildTool/bin/Release/net8.0/linux-x64/publish/SyatiModuleBuildTool SyatiModuleBuildTool/bin/Release/net8.0/linux-x64/publish/SyatiModuleBuildTool-linux
          mv SyatiModuleBuildTool/bin/Release/net8.0/osx-x64/publish/SyatiModuleBuildTool SyatiModuleBuildTool/bin/Release/net8.0/osx-x64/publish/SyatiModuleBuildTool-macos

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: auto
          title: "Auto"
          prerelease: false
          files: |
            SyatiModuleBuildTool/bin/Release/net8.0/win-x64/publish/SyatiModuleBuildTool.exe
            SyatiModuleBuildTool/bin/Release/net8.0/linux-x64/publish/SyatiModuleBuildTool-linux
            SyatiModuleBuildTool/bin/Release/net8.0/osx-x64/publish/SyatiModuleBuildTool-macos